listen: ":8080"
log_file: ./rebuild.log

directories:
  content: ../../site/content
  uploads: /tmp/cosy-uploads
  auth: ./auth

site:
  name: Cosy Posts
  # build_command: cd ../../site && hugo build
  base_url: https://example.org

email:
  from: system@example.org
  resend_api_key: ""
