# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/jphastings/cosy-posts/api/info.Version={{.Version}}
      - -X github.com/jphastings/cosy-posts/api/info.GitSHA={{.ShortCommit}}
    goos:
      - linux
      - darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - image_templates:
      - "ghcr.io/jphastings/cosy-posts:{{ .Version }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.version={{ .Version }}"
    goarch: amd64

  - image_templates:
      - "ghcr.io/jphastings/cosy-posts:{{ .Version }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.version={{ .Version }}"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/jphastings/cosy-posts:{{ .Version }}"
    image_templates:
      - "ghcr.io/jphastings/cosy-posts:{{ .Version }}-amd64"
      - "ghcr.io/jphastings/cosy-posts:{{ .Version }}-arm64"
  - name_template: "ghcr.io/jphastings/cosy-posts:latest"
    image_templates:
      - "ghcr.io/jphastings/cosy-posts:{{ .Version }}-amd64"
      - "ghcr.io/jphastings/cosy-posts:{{ .Version }}-arm64"

homebrew_casks:
- name: cosy-posts
  repository:
    owner: jphastings
    name: homebrew-tools
    token: "{{ .Env.GH_TOKEN }}"
  homepage: "https://github.com/jphastings/cosy-posts"
  url:
    verified: github.com/jphastings/cosy-posts
  description: "Create a private online space to share photos, videos, audio and notes with a closed circle of friends."
  license: "MIT"
