# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/jphastings/cosy-posts/api/info.Version={{.Version}}
      - -X github.com/jphastings/cosy-posts/api/info.GitSHA={{.ShortCommit}}
    goos:
      - linux
      - darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers_v2:
  - images:
      - "ghcr.io/jphastings/cosy-posts"
    tags:
      - "v{{ .Version }}"
      - latest
    labels:
      "org.opencontainers.image.title": "cosy-posts"
      "org.opencontainers.image.description": "A private space to share photos, videos, audio and notes with a closed circle of friends"
      "org.opencontainers.image.url": "https://github.com/jphastings/cosy-posts"
      "org.opencontainers.image.source": "https://github.com/jphastings/cosy-posts"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.licenses": "MIT"

homebrew_casks:
- name: cosy-posts
  repository:
    owner: jphastings
    name: homebrew-tools
    token: "{{ .Env.GH_TOKEN }}"
  homepage: "https://github.com/jphastings/cosy-posts"
  url:
    verified: github.com/jphastings/cosy-posts
  description: "Create a private online space to share photos, videos, audio and notes with a closed circle of friends."
  license: "MIT"
