//go:build pact

package main

import (
	"encoding/json"
	"fmt"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/jphastings/cosy-posts/api/config"

	"github.com/pact-foundation/pact-go/v2/models"
	"github.com/pact-foundation/pact-go/v2/provider"
)

// TestPactProvider verifies the API server satisfies the consumer pact.
//
// The pact file is generated by the Swift consumer tests (PactSwift) and
// checked into contracts/. This test starts the real server (via newHandler)
// and replays each interaction, verifying the server responds correctly.
func TestPactProvider(t *testing.T) {
	pactFile := filepath.Join("..", "contracts", "CosyPostsApp-CosyPostsAPI.json")
	if _, err := os.Stat(pactFile); os.IsNotExist(err) {
		t.Skipf("Pact file not found at %s — run Swift consumer tests first", pactFile)
	}

	contentDir := t.TempDir()
	authDir := t.TempDir()
	uploadDir := t.TempDir()

	// Create required auth CSV files.
	writeFile(t, filepath.Join(authDir, "can-post.csv"), "test@example.com\n")
	writeFile(t, filepath.Join(authDir, "can-view.csv"), "viewer@example.com\n")

	cfg := &config.Config{
		Listen:     ":0",
		ContentDir: contentDir,
		AuthDir:    authDir,
		UploadDir:  uploadDir,
	}
	cfg.Site.Name = "Test Site"
	cfg.Email.From = "test@example.com"
	cfg.Email.ResendAPIKey = "re_test_fake"

	handler, err := newHandler(cfg)
	if err != nil {
		t.Fatal(err)
	}

	server := httptest.NewServer(handler)
	defer server.Close()

	verifier := provider.NewVerifier()

	err = verifier.VerifyProvider(t, provider.VerifyRequest{
		Provider:        "CosyPostsAPI",
		ProviderBaseURL: server.URL,
		PactFiles:       []string{pactFile},

		StateHandlers: models.StateHandlers{

			// Auth states
			"a valid magic link token exists for test@example.com": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				if setup {
					token := "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
					tokenData := fmt.Sprintf(`{"email":"test@example.com","expiry":%q}`,
						time.Now().Add(15*time.Minute).Format(time.RFC3339))
					tokDir := filepath.Join(authDir, "tokens")
					os.MkdirAll(tokDir, 0o755)
					os.WriteFile(filepath.Join(tokDir, token), []byte(tokenData), 0o600)
				}
				return nil, nil
			},

			"no valid token exists": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				return nil, nil
			},

			"test@example.com is an authorized user": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				return nil, nil
			},

			"no session exists": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				return nil, nil
			},

			// Site info state
			"the site has content": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				if setup {
					createSession(t, authDir, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "test@example.com", "post")
				}
				return nil, nil
			},

			// Upload states
			"the user is signed in with post access": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				if setup {
					createSession(t, authDir, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "test@example.com", "post")
				}
				return nil, nil
			},

			"the user is signed in with view-only access": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				if setup {
					createSession(t, authDir, "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "viewer@example.com", "view")
				}
				return nil, nil
			},

			"an upload resource exists": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				if setup {
					createSession(t, authDir, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "test@example.com", "post")
					createTUSUpload(t, uploadDir, "upload123", 1024)
				}
				return nil, nil
			},

			"an upload resource exists with some data": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				if setup {
					createSession(t, authDir, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "test@example.com", "post")
					createTUSUpload(t, uploadDir, "upload123", 1024)
				}
				return nil, nil
			},

			// Post management states
			"post abc123def456ghi789jkl exists": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				if setup {
					createSession(t, authDir, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "test@example.com", "post")
					postDir := filepath.Join(contentDir, "2026", "03", "18", "abc123def456ghi789jkl")
					os.MkdirAll(postDir, 0o755)
					os.WriteFile(filepath.Join(postDir, "index.md"), []byte("---\ndate: 2026-03-18\n---\nHello"), 0o644)
				}
				return nil, nil
			},

			"no post with that ID exists": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				if setup {
					createSession(t, authDir, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "test@example.com", "post")
				}
				return nil, nil
			},

			// Access request states
			"there are pending access requests": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				if setup {
					createSession(t, authDir, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "test@example.com", "post")
					writeFile(t, filepath.Join(authDir, "wants-account.csv"), "user@example.com\n")
				}
				return nil, nil
			},

			"newuser@example.com has requested access": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				if setup {
					createSession(t, authDir, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "test@example.com", "post")
					writeFile(t, filepath.Join(authDir, "wants-account.csv"), "newuser@example.com\n")
				}
				return nil, nil
			},

			"reject@example.com has requested access": func(setup bool, s models.ProviderState) (models.ProviderStateResponse, error) {
				if setup {
					createSession(t, authDir, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "test@example.com", "post")
					writeFile(t, filepath.Join(authDir, "wants-account.csv"), "reject@example.com\n")
				}
				return nil, nil
			},
		},
	})

	if err != nil {
		t.Fatal(err)
	}
}

func createSession(t *testing.T, authDir, sessionID, email, role string) {
	t.Helper()
	sessDir := filepath.Join(authDir, "sessions")
	os.MkdirAll(sessDir, 0o755)
	data, _ := json.Marshal(map[string]string{
		"email":   email,
		"role":    role,
		"created": time.Now().Format(time.RFC3339),
	})
	os.WriteFile(filepath.Join(sessDir, sessionID), data, 0o600)
}

func createTUSUpload(t *testing.T, uploadDir, uploadID string, size int64) {
	t.Helper()
	infoData, _ := json.Marshal(map[string]any{
		"ID":       uploadID,
		"Size":     size,
		"Offset":   0,
		"MetaData": map[string]string{},
		"Storage": map[string]string{
			"Type": "filestore",
			"Path": filepath.Join(uploadDir, uploadID),
		},
	})
	os.WriteFile(filepath.Join(uploadDir, uploadID+".info"), infoData, 0o644)
	os.WriteFile(filepath.Join(uploadDir, uploadID), []byte{}, 0o644)
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
